export const error: string;
export const addButton: string;
export const modal: string;
export const form: string;
export const search: string;
export const buttonBlock: string;
export const deleteButton: string;
export const avatar: string;
export const wrapper: string;
