export const layout: string;
export const chatField: string;
export const chatWrapper: string;
export const chatList: string;
export const headerWrapper: string;
export const search: string;
export const searchWrapper: string;
export const searchIcon: string;
export const profileButton: string;
